[project]
name = "beacon-search-v2"
version = "0.1.0"
description = "Beacon Search backend rewritten with optimization and maintainability in mind"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "rapidfuzz>=3.10.1",
    "uvicorn>=0.34.0",
]
